### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [vladmeh/Movies_oAuth_Social#20]
Отличная работа:
1. [Вот эти значения](https://github.com/vladmeh/Movies_oAuth_Social/blob/1c181bc59f38cc06ac09b651dc58ef4afcac2689/auth/src/app.py#L42) хоста и номера порта нужно отправить в настройки и переменные окружения. Это изменяемые значения, их не нужно хардкодить.
2. [Этот метод](https://github.com/vladmeh/Movies_oAuth_Social/blob/1c181bc59f38cc06ac09b651dc58ef4afcac2689/admin/users/auth.py#L30) бросается исключениями если не может достучаться до хоста назначения. Исключение нужно поймать и обработать.
![282288183-79202d49-15c2-4542-ba8e-e7e9bb4ecd24-7](https://github.com/vladmeh/Movies_oAuth_Social/assets/73478414/211bf18c-7643-4475-b81b-8761d9359326)

**Comment by Uzatte** [comment]
Благодарим за ревью!

1. Настройки подключения джагера вынесли в переменные окружения,
2. Добавили обработку исключений на ошибку подключения.

**Comment by BigDeepBlue** [comment]
LGTM
